package IbexFarm::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

use IbexFarm;

__PACKAGE__->config(
    schema_class => 'IbexFarm::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=' . IbexFarm->config->{db_name} .
               ';host=' . IbexFarm->config->{db_host} .
               ';port=' . IbexFarm->config->{db_port},
        user => IbexFarm->config->{db_user},
        password => IbexFarm->config->{db_password},
        AutoCommit => 0,
    }
);

=head1 NAME

IbexFarm::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<IbexFarm>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<IbexFarm::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Alex Drummond

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
